### ISSUE TITLE
Test on GTA Dataset

### ISSUE THREAD

**Issue by PeidongLi** [xjqicuhk/SIMS#1]
I wonder how can I test this method on GTA Dataset as mentioned in the paper. I tried to just change the semantic layouts but I failed when generated the canvas. Thank you!

**Comment by xjqicuhk** [comment]
i will update this soon!

leeace <notifications@github.com>于2018年5月24日 周四下午5:00写道：

**Comment by xjqicuhk** [comment]
The test code on gta5 dataset has already updated.
