### ISSUE TITLE
Undefined function 'save_warper5' in search_segments.m

### ISSUE THREAD

**Issue by wheatdog** [xjqicuhk/SIMS#2]
As title.

**Comment by xjqi** [comment]
Updated.

**Comment by wheatdog** [comment]
Thanks for the quick update. I have another related issue: reference to non-existent field 'proposal_iou_all'  in https://github.com/xjqicuhk/SIMS/blob/master/matlab_code/test_generate_transform.m#L62

I run into this issue after applying `search_segments.m` on my own data and running `test_generate_transform`.

**Comment by xjqi** [comment]
Currently, change "proposal_iou_all" to "proposal_iou". You can first try this. I still do not update this part. Will update soon.

**Comment by wheatdog** [comment]
OK.
I have few more questions about https://github.com/xjqicuhk/SIMS#inference.

1. It said "Use resolution "512 x 1024" as a running example", but I found 256x512 in 
    - https://github.com/xjqicuhk/SIMS/blob/master/matlab_code/test_connect_component_mask.m#L30-L31
    - https://github.com/xjqicuhk/SIMS/blob/master/matlab_code/search_segments.m#L13-L15
2. While running `transformation.py` in `python_code`. It complains about missing folder in `../traindata/label_refine512`. It seems not in [traindata.zip](https://drive.google.com/file/d/1UoZ2_TnA-IrRLtgvvznUO3VZbOwXwZI-/view). And the resolution setting in `transformation.py` is "512x1024".

Did I do something wrong here? I am confused.

**Comment by xjqi** [comment]
(1) In  this case, we only save the patches to save memory and speed up
search ,when using higher resolution, we simply read the original high
resolution images, and get the corresponding patch by upsampling the mask.
(2) We have updated the code several days agao, please refer the readme
part. You should run "resize_transform.m" before proceeding.

**Comment by wheatdog** [comment]
Thank for your kindly help! It kinda works.
