### ISSUE TITLE
Slow processing speed of train_generate_synthesis.m on 256*512 training data

### ISSUE THREAD

**Issue by hliuav** [xjqicuhk/SIMS#4]
When I run train_generate_synthesis.m on 256*512 training data, it takes about 3 mins to process 1 picture. Is this speed normal or something is going wrong?

**Comment by xjqicuhk** [comment]
I should not take that much time. You can reduce the number 100 in  Line 104  " while( count<100)" to a smaller value. This will reduce the time greatly without sacrifacing the result.
